// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/hhhhkkk/mini-blog/v1/config"
	"github.com/hhhhkkk/mini-blog/v1/internal/app"
	admin2 "github.com/hhhhkkk/mini-blog/v1/internal/app/admin"
	api2 "github.com/hhhhkkk/mini-blog/v1/internal/app/api"
	"github.com/hhhhkkk/mini-blog/v1/internal/biz"
	"github.com/hhhhkkk/mini-blog/v1/internal/biz/admin"
	"github.com/hhhhkkk/mini-blog/v1/internal/biz/api"
	"github.com/hhhhkkk/mini-blog/v1/internal/data"
	"github.com/hhhhkkk/mini-blog/v1/internal/http"
	admin3 "github.com/hhhhkkk/mini-blog/v1/internal/http/admin"
	api3 "github.com/hhhhkkk/mini-blog/v1/internal/http/api"
	"github.com/hhhhkkk/mini-blog/v1/internal/http/middleware"
	"github.com/hhhhkkk/mini-blog/v1/internal/job"
)

// Injectors from provider.go:

func InitApp() (*App, error) {
	engine := NewEngine()
	configConfig := config.NewServerConfig()
	v := job.NewJobGroupProvider()
	v2 := middleware.NewBaseMiddleware(configConfig)
	logger := NewLogger()
	db := data.NewDB(configConfig)
	adminUserRepoImpl := data.NewAdminUserRepoImpl(db)
	userBiz := admin.NewUserBiz(logger, adminUserRepoImpl)
	userCase := admin2.NewUserCase(userBiz)
	controller := admin3.NewUserController(userCase)
	loginController := admin3.NewLoginController(userCase)
	userRepoImpl := data.NewUserRepoImpl(db)
	identityRepoImpl := data.NewIdentityRepoImpl(db)
	inviteRecordRepoImpl := data.NewInviteRecordRepoImpl(db)
	apiUserBiz := api.NewUserBiz(userRepoImpl, identityRepoImpl, inviteRecordRepoImpl)
	apiUserCase := api2.NewUserCase(apiUserBiz)
	userController := api3.NewUser(apiUserCase)
	v3 := http.NewRouterProvider(controller, loginController, userController)
	app := NewApp(engine, configConfig, v, v2, v3, logger)
	return app, nil
}

// provider.go:

func NewEngine() *gin.Engine {
	return gin.New()
}

var ProviderSet = wire.NewSet(
	NewLogger, http.RouterProviderSet, app.ProviderSet, middleware.ProviderSet, biz.ProviderSet, data.ProviderSet, config.ProviderSet, job.ProviderSet, NewEngine,
	NewApp,
)
