// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/hhhhkkk/mini-blog/config"
	"github.com/hhhhkkk/mini-blog/internal/biz"
	"github.com/hhhhkkk/mini-blog/internal/data"
	"github.com/hhhhkkk/mini-blog/internal/http"
	"github.com/hhhhkkk/mini-blog/internal/http/middleware"
	"github.com/hhhhkkk/mini-blog/internal/job"
)

// Injectors from provider.go:

func InitApp() (*App, error) {
	engine := NewEngine()
	appConfig := config.NewAppConfig()
	v := job.NewJobGroupProvider()
	v2 := middleware.NewBaseMiddleware(appConfig)
	v3 := http.NewRouterProvider()
	app := NewApp(engine, appConfig, v, v2, v3)
	return app, nil
}

// provider.go:

func NewEngine() *gin.Engine {
	return gin.New()
}

var ProviderSet = wire.NewSet(http.RouterProviderSet, middleware.ProviderSet, biz.ProviderSet, data.ProviderSet, config.ProviderSet, job.ProviderSet, NewEngine,
	NewApp,
)
