// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/hhhhkkk/mini-blog/v2/internal/app"
	"github.com/hhhhkkk/mini-blog/v2/internal/router"
)

// Injectors from provider.go:

func InitApp() (*App, error) {
	engine := NewEngine()
	appService := app.NewAppService()
	routerRouter := router.NewRouter(appService)
	internalApp := NewApp(engine, routerRouter)
	return internalApp, nil
}

// provider.go:

func NewEngine() *gin.Engine {
	return gin.Default()
}

var Provider = wire.NewSet(NewEngine, NewApp, app.ProviderSet, router.ProviderSet)
