// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/hhhhkkk/mini-blog/v2/config"
	"github.com/hhhhkkk/mini-blog/v2/internal/app"
	"github.com/hhhhkkk/mini-blog/v2/internal/cache"
	"github.com/hhhhkkk/mini-blog/v2/internal/router"
	"github.com/hhhhkkk/mini-blog/v2/internal/service"
	"github.com/hhhhkkk/mini-blog/v2/internal/service/consistency_hash"
	"github.com/hhhhkkk/mini-blog/v2/internal/service/expired_strategy"
)

// Injectors from provider.go:

func InitApp() (*App, error) {
	engine := NewEngine()
	appService := app.NewAppService()
	configConfig := config.New()
	expiredConfig := config.NewExpiredConfig(configConfig)
	iExpiredStrategy := expired_strategy.NewExpiredStrategyImpl(expiredConfig)
	myHash := consistencyhash.New()
	cacheService := cache.NewCacheService(iExpiredStrategy, myHash)
	routerRouter := router.NewRouter(appService, cacheService)
	internalApp := NewApp(engine, routerRouter)
	return internalApp, nil
}

// provider.go:

func NewEngine() *gin.Engine {
	return gin.Default()
}

var Provider = wire.NewSet(NewEngine, NewApp, app.ProviderSet, router.ProviderSet, cache.ProviderSet, service.ProviderSet, config.ProviderSet)
